
name: $(BuildDefinitionName)_$(date:yyyyMMdd)_$(Build.SourceBranchName)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Release_Production
  variables:  
  - name: TESTAPPURL
    value: 'https://mytestapp.dev.com'
  jobs:
  - deployment: Deploy_TestApp_Production
    environment: testapp-prod.testapp-prod
    strategy:
      runOnce:
        deploy:
          steps:
          - template: build-templates/init-deployment.yml